---
title: "Cours 4 : Structures arborescentes"
format:
  html:
    code-fold: true
---

# Introduction : arbres binaires

En informatique, un *graphe* est composé d'un ensemble fini de *sommets*, et d'un ensemble d'arêtes qui relient deux sommets.

> Il s'agit d'une famille d'objets fondamentaux en informatique, et en sciences plus généralement, car leurs applications sont innombrables : modélisation de réseaux physiques (routes, labyrinthes), de réseaux sociaux, systèmes de contraintes, structure de molécules, bases de données...

Un *arbre* est un graphe *connexe* (en un seul morceau) ne contenant pas de cycle d'arêtes. En algorithmique, une des structures de données les plus utilisées est *l'arbre binaire*, c'est-à-dire un arbre dont chaque sommet a au plus $3$ voisins. Cette structure possède de nombreux avantages en termes de complexité, que nous allons voir.

## Définition

En algorithmique, un **arbre binaire** (*binary tree*) est défini comme suit :

- Il est composé de **noeuds** (*node*) contenant des valeurs.
- L'un des noeuds est appelé la **racine** (*root*) de l'arbre. On la représente généralement en haut de l'arbre.
- Chaque noeud peut être relié à deux noeuds que l'on appelle **fils gauche** et **fils droit** (*left* et *right child*).
- Si un noeud n'est pas la racine, il est le fils gauche ou droit d'un autre noeud, son **parent**.
- Un noeud qui n'a pas de fils gauche ni de fils droit est appelé **feuille** (*leaf*, *leaves* au pluriel) de l'arbre. Elles sont généralement représentées en bas de l'arbre. Les noeuds qui ne sont pas des feuilles sont appelés **noeud interne** de l'arbre.

Exemple d'arbre binaire :

```{mermaid}
%%| fig-align: center
%%| label: fig-bintree
%%| fig-cap: Exemple d'arbre binaire
stateDiagram
	A0: 4
	A1: 5
	A2: 3
	A3: 2
	A1 --> A2: left
	A1 --> A3: right
	A4: 1
	A5: 9
	A6: 8
	A7: 6
	A5 --> A6: left
	A5 --> A7: right
	A8: 7
	A4 --> A5: left
	A4 --> A8: right
	A0 --> A1: left
	A0 --> A4: right
```

Dans la @fig-bintree, la racine contient la valeur $4$. L'arbre contient $5$ feuilles, contenant les valeurs $3$, $2$, $8$, $6$, $7$.

## Implémentations

Nous proposons deux implémentations des arbres binaires en C. La première est une implémentation proche des listes chaînées, avec des noeuds reliés entre eux par des pointeurs, et la seconde utilise un tableau contenant les valeurs, et les liaisons sont définies implicitement par l'ordre dans le tableau.

### Implémentation par pointeurs

L'implémentation proposée dans le TP4 est la suivante :

```C
typedef int T; // Type des données

typedef struct s_node {
    struct s_node *left;  // Fils gauche
    struct s_node *right; // Fils droit
    T value;              // Valeur
} t_node;

typedef struct {
    t_node *root; // Pointeur vers la racine
} t_tree;
```

Un noeud contient deux pointeurs vers ses fils gauche et droit (éventuellement ``NULL``) et une valeur de type ``T``, ici un alias de ``int``. L'objet arbre contient un pointeur vers le noeud racine.

On se dote d'une fonction qui crée un noeud contenant une valeur ``value`` donnée, de la même manière que pour les cellules des listes chaînées.

```C
// Renvoie l'adresse d'un noeud alloué dynamiquement
t_node *create_node(T value) {
    t_node *node = malloc(sizeof(t_node));
    node->left  = NULL;
    node->right = NULL;
    node->value = value;
    return node;
}
```

Nous verrons la fonction d'insertion d'une valeur dans la partie sur les arbres binaires de recherche ci-dessous.

Un arbre binaire peut être parcouru avec la fonction récursive suivante :

```C
// Affichage des valeurs contenues dans l'arbre

// Fonction auxiliaire récursive : prend un noeud en paramètre
void print_tree_aux(t_node *node) {
	if (node->left != NULL) {
		print_tree_aux(node->left);
	}
	printf("%d ", node->value);
	if (node->right != NULL) {
		print_tree_aux(node->right);
	}
}

// Fonction prinicpale : appelle simplement la fonction auxiliaire
void print_tree_values(t_tree *tree) {
	if (tree->root != NULL) {
		print_tree_aux(tree->root);
	}
	printf("\n");
}
```

Cette fonction va parcourir tous les noeuds du fils gauche du noeud actuel, puis afficher la valeur du noeud, et enfin parcourir tous les noeuds du fils droit. Ce parcours est un **parcours en profondeur** : il consiste à descendre en ligne droite jusqu'à un cul-de-sac, puis de remonter (*backtrack*), et de redescendre à nouveau, et ainsi de suite.

Le parcours tel qu'implémenté ici affiche les valeurs dans **l'ordre infixe**. Pour l'arbre de la @fig-bintree, la fonction affiche ``3 5 2 4 8 9 6 1 7``.

> L'ordre infixe des valeurs d'un arbre binaire est analogue à la *notation infixe* des expressions arithmétiques, comme vu dans le TP2. En effet, si un arbre binaire contient des opérandes (nombres) sur les feuilles et des opérateurs sur les noeuds internes, alors l'affichage dans l'ordre infixe produira une expression en notation infixe.
> Par exemple, l'arbre ci-dessous :
```{mermaid}
%%| fig-align: center
%%| label: fig-expr
stateDiagram
	A0: \+
	A1: \*
	A2: 2
	A3: 3
	A1 --> A2
	A1 --> A3
	A4: \/
	A5: \*
	A6: 4
	A7: 5
	A5 --> A6
	A5 --> A7
	A8: 2
	A4 --> A5
	A4 --> A8
	A0 --> A1
	A0 --> A4
```
> Produit l'affichage ``2 * 3 + 4 * 5 / 2``. Il s'agit bien de la notation infixe usuelle.
> Si l'on choisit d'afficher le fils gauche, puis le fils droit, puis la valeur du noeud courant (l'instruction ``printf`` est située après les deux appels récursifs), alors la notation affichée est la notation *postfixée* de la même expression, donc la fameuse *notation polonaise inversée* (RPN) vue dans le TP2 : ``2 3 * 4 5 * 2 / +``.

### Implémentation par tableau

Une autre implémentation possible utilise des tableaux. L'arbre représenté est forcément *presque complet*, c'est-à-dire que tous les niveaux de l'arbre sont complets, sauf éventuellement le dernier, et dans ce cas le dernier niveau est rempli de gauche à droite.

```{mermaid}
%%| fig-align: center
%%| label: fig-tree2
%%| fig-cap: Exemple d'arbre binaire presque complet
stateDiagram
	A0: 0
	A1: 1
	A2: 3
	A3: 4
	A1 --> A2
	A1 --> A3
	A4: 2
	A5: 5
	A6: 7
	A7: 8
	A2 --> A6
	A2 --> A7
	A8: 6
	A9: 9
	A10: 10
	A4 --> A5
	A4 --> A8
	A0 --> A1
	A0 --> A4
	A3 --> A9
	A3 --> A10
```

Lorsque l'on implémente un arbre binaire avec un tableau, il est commode de placer les noeuds comme dans la @fig-tree2 :

- la racine en position $0$.
- Le noeud en position $i$ a son fils gauche en position $2i+1$ et son fils droit en position $2i+2$.
- Le parent du noeud en position $i$ est en position $(i - 1)/2$.

Dans certains cas, cette implémentation est plus pratique que la précédente, par exemple, pour implémenter la structure de *tas binaire*, un type d'arbre presque complet.

Un exemple d'implémentation en C de cette représentation.

```C
typedef struct {
	T *values;    // Valeurs présentes dans l'arbre
	int nb_nodes; // Nombre de noeuds
} t_tree_alt;

// max = nombre maximum de noeuds
t_tree_alt create_tree(int max) {
	t_tree_alt tree;
	tree.values = malloc(max * sizeof(T));
	tree.nb_nodes = 0;
	return tree;
}

int parent_index(int i) {
  	return (i - 1) / 2;
}

int left_child_index(int i) {
  	return 2 * i + 1;
}

int right_child_index(int i) {
  	return 2 * i + 2;
}
```

Le parcours en profondeur de l'arbre peut se réaliser de la même manière que précédemment :

```C
// Affichage des valeurs contenues dans l'arbre en ordre infixe

// Fonction auxiliaire récursive : prend un indice (noeud) en paramètre
void print_tree_alt_aux(t_tree_alt *tree, int i) {
	int i_left = left_child_index(i);
	int i_right = right_child_index(i);
	// Le fils gauche est vide si son indice dépasse nb_nodes
	if (i_left < tree->nb_nodes) {
		print_tree_alt_aux(tree, i_left);
	}
	printf("%d ", tree->values[i]);
	// Idem pour le fils droit
	if (i_right < tree->nb_nodes) {
		print_tree_alt_aux(tree, i_right);
	}
}

// Fonction prinicpale : appelle simplement la fonction auxiliaire
void print_tree_alt_values(t_tree_alt *tree) {
	if (tree->nb_nodes > 0) {
		print_tree_alt_aux(tree->root);
	}
	printf("\n");
}
```

En revanche, le **parcours en largeur** de l'arbre est immédiat avec cette représentation.

```C
// Parcours en largeur (Breadth-first search)
void print_bfs(t_tree_alt *tree) {
  	for (int i = 0; i < tree->nb_nodes; i++) {
		printf("%d ", tree->values[i]);
  	}
  	printf("\n");
}
```

Le parcours en largeur consiste à partir de la racine, parcourir ses voisins, puis les voisins de ces noeuds, puis leurs voisins, etc. en terminant par les feuilles. Dans la représentation par tableaux, les valeurs sont déjà stockées dans le tableau dans l'ordre de parcours en largeur, il suffit donc de les afficher dans l'ordre.

# Arbres binaires de recherche

## Définition

Un **arbre binaire de recherche** (*binary search tree*, BST) est un arbre binaire dans lequel, pour chaque noeud contenant une valeur (numérique) $v$ :

- Toutes les valeurs contenues dans le fils gauche du noeud sont inférieures ou égales à $v$.
- Toutes les valeurs contenues dans le fils droit du noeud sont supérieures strictement à $v$.

Cette structure très simple permet d'ajouter et de rechercher une valeur plus efficacement, à la manière d'une recherche dichotomique.

## Opérations

Pour implémenter les opérations, nous allons utiliser la première représentation en mémoire des arbres binaires, avec des ``t_node`` reliés entre eux par des pointeurs.

### Ajout d'une valeur

L'ajout d'une valeur à l'arbre doit préserver la propriété d'être un arbre binaire de recherche.

- On insère (récursivement) dans le fils gauche si la valeur du noeud courant est supérieure à la valeur à insérer, sinon on insère dans le fils droit.
- On descend jusqu'à trouver un emplacement vide.

On peut écrire la fonction de manière récursive :

```C
// Fonction auxiliaire
void add_value_aux(t_node *node, T value) {
	if (value <= node->value) {
		// insérer à gauche
		if (node->left == NULL) {
			// insertion possible ici
			node->left = create_node(value);
		}
		else {
			// appel récursif dans le fils gauche
			add_value_aux(node->left, value);
		}
	}
	else {
		// insérer à droite
		if (node->right == NULL) {
			// insertion possible ici
			node->right = create_node(value);
		}
		else {
			// appel récursif dans le fils droit
			add_value_aux(node->right, value);
		}
	}
}

// Fonction principale
void add_value(t_tree *tree, T value) {
	if (tree->root == NULL) {
		tree->root = create_node(value);
	}
	else {
		add_value_aux(tree->root, value);
	}
	tree->nb_nodes++;
}
```

### Recherche d'une valeur

L'avantage des arbres binaires de recherche est de pouvoir effectuer... des recherches d'éléments efficacement.

Comme pour l'insertion, on cherche à gauche ou à droite en fonction du résultat de la comparaison de la valeur recherchée et de la valeur du noeud courant.

```C
bool is_present_aux(t_node *node, T value) {
	if (node == NULL) {
		return false;
	}
	if (node->value == value) {
		return true;
	}
	if (value < node->value) {
		return is_present_aux(node->left, value);
	}
	else {
		return is_present_aux(node->right, value);
	}
}

bool is_present(t_tree *tree, T value) {
	return is_present_aux(tree->root, value);
}
```

Ou de manière plus concise :
```C
bool is_present_aux(t_node *node, T value) {
	return node != NULL // cas d'arrêt négatif
		&& (node->value == value // cas d'arrêt positif
		|| is_present(value < node->value ? node->left : node->right, value));
		// appel récursif à gauche ou à droite
}
```


## Complexité

Les opérations de recherche et d'ajout dans un arbre binaire de recherche s'effectuent en descendant de fils en fils jusqu'à trouver la valeur recherchée ou un emplacement vide.

Il est donc naturel de considérer la **hauteur** d'un arbre binaire : la longueur (en nombre d'arêtes) du plus long chemin entre la racine est une feuille. Par exemple, tous les arbres illustrés dans ce cours ont une hauteur de $3$.

**La complexité** des opérations d'ajout et de recherche est donc **proportionnelle à la hauteur de l'arbre.**

Donnons un encadrement de la hauteur $h$ d'un arbre lorsque celui-ci possède $n$ sommets.

Dans le meilleur cas, l'arbre est *complet*, c'est-à-dire que tous ses niveaux sont remplis : l'arbre possède $2^i$ noeuds à chaque niveau, donc possède $\displaystyle n = \sum_{i = 0}^h 2^i = 2^{h + 1} - 1$ noeuds. On a donc $\displaystyle h = \left\lfloor \log_2(n + 1)\right\rfloor - 1 = O(\log n)$. La hauteur est **logarithmique** en le nombre de noeuds.

En revanche, en pire cas, chaque noeud possède un fils droit et pas de fils gauche, par exemple :

```{mermaid}
%%| fig-align: center
%%| label: fig-peigne
%%| fig-cap: Exemple de *peigne*
stateDiagram
	A0: 0
	A0l: _
	A1: 1
	A1l: _
	A2: 2
	A2l: _
	Anm1: n - 1
	Anm1l: _
	An: n
	A0 --> A0l
	A0 --> A1
	A1 --> A1l
	A1 --> A2
	A2 --> A2l
	A2 --> Anm1: ...
	Anm1 --> Anm1l
	Anm1 --> An
```

L'arbre de la @fig-peigne possède $n+1$ noeuds et est de hauteur $n$. On a donc une hauteur **linéaire** en le nombre de noeuds en pire cas.

Nos fonctions d'ajout et de recherche sont donc **linéaires** ($O(n)) en pire cas. Cette complexité n'est donc pour le moment pas meilleure qu'une simple liste chaînée.

# Arbres binaires de recherche équilibrés : arbres AVL

Les deux arbres suivants sont des arbres binaires de recherche contenant les mêmes valeurs :

```{mermaid}
%%| fig-align: center
%%| label: fig-unbalanced
stateDiagram
	A0: 0
	A0l: _
	A1: 1
	A1l: _
	A2: 2
	A2l: _
	Anm1: 98
	Anm1l: _
	An: 99
	A0 --> A0l
	A0 --> A1
	A1 --> A1l
	A1 --> A2
	A2 --> A2l
	A2 --> Anm1: ...
	Anm1 --> Anm1l
	Anm1 --> An
```

```{mermaid}
%%| fig-align: center
%%| label: fig-balanced
stateDiagram
	A0: 50
	A1: 25
	A2: 13
	A3: 38
	A1 --> A2
	A1 --> A3
	A4: 75
	A5: 63
	A6: 0
	A7: 24
	A2 --> A6: ...
	A2 --> A7: ...
	A8: 88
	A9: 26
	A10: 49
	A4 --> A5
	A4 --> A8
	A0 --> A1
	A0 --> A4
	A3 --> A9: ...
	A3 --> A10: ...
	A11: 51
	A12: 74
	A13: 76
	A14: 99
	A5 --> A11: ...
	A5 --> A12: ...
	A8 --> A13: ...
	A8 --> A14: ...
```

En revanche, le premier a une hauteur linéaire en le nombre de noeuds, alors que le second a une hauteur logarithmique. On dit qu'il est **équilibré**.

Nous avons tout intérêt à considérer des arbres équilibrés, afin de garantir des opérations d'ajout et de recherche de complexité logarithmique. Malheureusement, cet équilibrage dépend de l'ordre d'insertion des éléments. Il nous faut donc considérer une opération d'insertion plus complexe, afin de maintenir la propriété d'équilibrage de l'arbre.


## Définition

La *hauteur* d'un arbre binaire est la longueur du plus long chemin entre une feuille et la racine. Par convention, un arbre vide a une hauteur de $-1$, un arbre $(v, Empty, Empty)$ est de hauteur $0$, et un arbre $T = (v, T_{left}, T_{right})$ a une hauteur $h(T) = 1 + \max(h(T_{left}), h(T_{right}))$.

Le *facteur d'équilibrage* (*balancing factor*) d'un arbre $T = (v, T_{left}, T_{right})$ est $bf(T) = h(T_{left}) - h(T_{right})$. On dit qu'un arbre $T = (v, T_{left}, T_{right})$ est *équilibré* si $bf(T) \in \{-1, 0, 1\}$ et $T_{left}$ et $T_{right}$ sont équilibrés.

Les arbres **AVL** sont des arbres binaires de recherche qui appliquent des opérations de *rotations* à chaque insertion, afin de maintenir l'équilibre de l'arbre. Ces opérations s'appliquent à n'importe quel noeud interne de l'arbre.

### Rotation à gauche

Dans une opération à **gauche**, la racine du sous-arbre (ici $u$) devient le **fils gauche** du sommet qui est initialement son fils droit (ici $v$).

::: {#fig-rotleft layout-ncol=3}

```{mermaid}
%%| fig-align: center
stateDiagram
	classDef subtree font-style:italic,font-weight:bold,fill:white
	U: u
	A: A
	U --> A:::subtree: left
	V: v
	B: B
	C: C
	U --> V: right
	V --> B:::subtree: left
	V --> C:::subtree: right
```

```{latex}





	   --> 
```

```{mermaid}
%%| fig-align: center
stateDiagram
    classDef subtree font-style:italic,font-weight:bold,fill:white
	V: v
	U: u
	A: A
	U --> A:::subtree: left
	B: B
	C: C
	V --> U: left
	U --> B:::subtree: right
	V --> C:::subtree: right
```

Rotation à gauche
:::

Cette opération préserve la propriété d'être un arbre binaire de recherche. En effet, on a bien préservé l'ordre des valeurs : celles du sous-arbre $A$ sont inférieures à $u$, qui est inférieur à $v$, qui est inférieur aux valeurs du sous-arbre $C$. Les valeurs du sous-arbre $B$ sont comprises entre $u$ et $v$.

### Rotation à droite

Dans une opération à **droite**, la racine du sous-arbre (ici $u$) devient le **fils droit** du sommet qui est initialement son fils gauche (ici $v$).

::: {#fig-rotright layout-ncol=3}

```{mermaid}
%%| fig-align: center
stateDiagram
	classDef subtree font-style:italic,font-weight:bold,fill:white
	U: u
	V: v
	U --> V: left
	A: A
	V --> A:::subtree: left
	B: B
	C: C
	V --> B:::subtree: right
	U --> C:::subtree: left
```

```{latex}





	   --> 
```

```{mermaid}
%%| fig-align: center
stateDiagram
	classDef subtree font-style:italic,font-weight:bold,fill:white
	
	V: v
	A: A
	V --> A:::subtree: left
	
	B: B
	C: C
	U: u
	V --> U: right
	U --> B:::subtree: left
	U --> C:::subtree: right
```

Rotation à droite
:::

De même, cette opération préserve la propriété que l'arbre est une arbre binaire de recherche.

### Règles

Après une insertion d'une valeur dans le fils $T_{left}$ ou $T_{right}$ d'un arbre $T = (v, T_{left}, T_{right})$, on recalcule le facteur d'équilibrage de $T_{left}$, $T_{right}$ et $T$, et on applique les règles suivantes :

- Si $bf(T) = -2$ :
	- Si $bf(T_{right}) = -1$: **rotation à gauche** de $T$
	- Sinon si $bf(T_{right}) = 1$: **rotation à droite** de $T_{right}$ puis **rotation à gauche** de $T$
- Sinon si $bf(T) = 2$:
	- Si $bf(T_{right}) = -1$: **rotation à gauche** de $T_{left}$ puis **rotation à droite** de $T$
	- Sinon si $bf(T_{right}) = 1$: **rotation à droite** de $T$
- Sinon, on ne fait rien.

Il faut appliquer ces opérations en remontant le long du chemin entre la racine et le noeud où a eu lieu l'insertion.

L'insertion des éléments $\{ 9, 1, 2, 4, 8, 3, 5, 0, 6, 7 \}$ dans cet ordre donnera l'arbre binaire de recherche suivant : 

```{mermaid}
%%| fig-align: center
%%| label: fig-avl
%%| fig-cap: Exemple d'arbre AVL
stateDiagram
	A0: 9 (h = 7, bf = 7)
	A1: 1 (h = 6, bf = -5)
	A2: 0 (h = 0, bf = 0)
	A3: _
	A4: _
	A2 --> A3: left
	A2 --> A4: right
	A5: 2 (h = 5, bf = -5)
	A6: _
	A7: 4 (h = 4, bf = -3)
	A8: 3 (h = 0, bf = 0)
	A9: _
	A10: _
	A8 --> A9: left
	A8 --> A10: right
	A11: 8 (h = 3, bf = 3)
	A12: 5 (h = 2, bf = -2)
	A13: _
	A14: 6 (h = 1, bf = -1)
	A15: _
	A16: 7 (h = 0, bf = 0)
	A17: _
	A18: _
	A16 --> A17: left
	A16 --> A18: right
	A14 --> A15: left
	A14 --> A16: right
	A12 --> A13: left
	A12 --> A14: right
	A19: _
	A11 --> A12: left
	A11 --> A19: right
	A7 --> A8: left
	A7 --> A11: right
	A5 --> A6: left
	A5 --> A7: right
	A1 --> A2: left
	A1 --> A5: right
	A20: _
	A0 --> A1: left
	A0 --> A20: right
```

mais l'AVL suivant :

```{mermaid}
stateDiagram
	A0: 4 (h = 3, bf = 0)
	A1: 2 (h = 2, bf = 1)
	A2: 1 (h = 1, bf = 1)
	A3: 0 (h = 0, bf = 0)
	A4: _
	A5: _
	A3 --> A4: left
	A3 --> A5: right
	A6: _
	A2 --> A3: left
	A2 --> A6: right
	A7: 3 (h = 0, bf = 0)
	A8: _
	A9: _
	A7 --> A8: left
	A7 --> A9: right
	A1 --> A2: left
	A1 --> A7: right
	A10: 8 (h = 2, bf = 1)
	A11: 6 (h = 1, bf = 0)
	A12: 5 (h = 0, bf = 0)
	A13: _
	A14: _
	A12 --> A13: left
	A12 --> A14: right
	A15: 7 (h = 0, bf = 0)
	A16: _
	A17: _
	A15 --> A16: left
	A15 --> A17: right
	A11 --> A12: left
	A11 --> A15: right
	A18: 9 (h = 0, bf = 0)
	A19: _
	A20: _
	A18 --> A19: left
	A18 --> A20: right
	A10 --> A11: left
	A10 --> A18: right
	A0 --> A1: left
	A0 --> A10: right
```

## Opérations

Nous devons modifier légèrement la définition de nos noeuds :

```C
typedef struct s_node {
    struct s_node *left;
    struct s_node *right;
    T value;
    int height;
    int bf;
} t_node;
```

Nous ne coderons pas la fonction d'insertion ici. A noter que pour garantir une bonne complexité, cette fonction doit calculer la hauteur et le facteur d'équilibrage récursivement en un seul parcours.

L'opération de rotation à gauche peut s'implémenter ainsi :

```C
// Renvoie la nouvelle racine du sous-arbre auquel on applique la rotation
t_node *rotate_left(t_node *root) {

	// Nommage des noeuds et du sous-arbre B
    t_node *u = root;
    t_node *v = u->right;
    t_node *b = v->left;

	// Mise à jour des pointeurs
    u->right = b;
    v->left = u;

	// Renvoi de la nouvelle racine
    t_node *new_root = v;
    return new_root;
}
```

## Complexité

Dans un arbre à $n$ sommets et de hauteur $h$ (que l'on suppose en $O(\log n)$) :

- les opérations de rotation à gauche et à droite s'effectuent en temps constant $O(1)$.
- Il faut faire au plus $h$ rotations de l'arbre pour réaliser une insertion (en plus du coût $O(h)$ d'une insertion classique dans un arbre binaire de recherche).
- La recherche d'une valeur dans un AVL est identique à la recherche dans un arbre binaire de recherche classique.

On peut montrer que l'insertion dans un AVL préserve la propriété que $h = O(n)$ après chaque insertion. **Les opérations d'insertion et de recherche sont donc de complexité logarithmique** $O(\log n)$ en le nombre de noeuds de l'arbre.

Ces opérations sont cette fois exponentiellement plus efficaces que l'opération de recherche dans une liste chaînée.

## Autres arbres de la littérature

Les arbres AVL ont été inventés en 1962 par les chercheur soviétiques Georgy Adelson-Velsky et Evgenii Landis. Il s'agit de la première structure d'arbre binaire auto-équilibrés.

Parmi les autres structures d'arbre auto-équilibrés, on peut mentionner les *B-trees* ou les *arbres rouges-noirs*.


